name: Build and deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.x
            8.x
          include-prerelease: true

      - name: dotnet restore
        run: dotnet restore --configuration Release 

      - name: dotnet build
        run: dotnet build --configuration Release --no-restore 

      - name: dotnet pack
        run: dotnet pack --configuration Release --no-build -o .${{env.DOTNET_ROOT}}/NuGet

      - name: Upload NuGet artifact
        uses: actions/upload-artifact@v3
        with:
          name: NuGet
          path: ${{env.DOTNET_ROOT}}/NuGet

  automerge:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: windows-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3.6.2

  # deploy-nuget:
  #   if: ${{ github.event_name != 'pull_request' }}
  #   runs-on: windows-latest
  #   needs: build
    
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: NuGet

  #     - name: Push NuGet
  #       run: dotnet nuget push ${{ github.workspace }}/*nupkg --source https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate
